### ISSUE TITLE
the reference is missing

### ISSUE THREAD

**Issue by ijitai** [naveensundarg/Common-Lisp-Actors#10]
The below ref is gone:

1. [Meta-Circular Adventures in Functional Abstraction –Challenging Clojure in Common Lisp] (http://chriskohlhepp.wordpress.com/metacircular-adventures-in-functional-abstraction-challenging-clojure-in-common-lisp/)

**Comment by naveensundarg** [comment]
Replaced with a snapshot for now.

https://hackerfall.com/story/challenging-clojure-in-common-lisp
